# Este es un flujo de trabajo básico para ayudarlo a comenzar con Acciones

nombre: Android Build CI

# Controla cuándo se ejecutará el flujo de trabajo

en: [push, pull_request, workflow_dispatch]

# Una ejecución de flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo

trabajos:

  # Este flujo de trabajo contiene un solo trabajo llamado "construir"

  construir:

    # El tipo de corredor en el que se ejecutará el trabajo

    se ejecuta en: ubuntu-latest

    

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo

    pasos:

      # Desprotege su repositorio en $GITHUB_WORKSPACE, para que su trabajo pueda acceder a él

      - usos: acciones/checkout@v2

      - usos: krdlab/setup-haxe@v1

        con:

          versión haxe: 4.2.3

          

      - nombre: Caché ruta haxelib

        usos: acciones/cache@v2

        con:

          camino: |

            %HAXELIB_ROOT%

          clave: ${{ runner.os }}-android

          

      - nombre: Configurar herramientas SDK de Android

        usos: android-actions/setup-android@v2.0.2

        

      - nombre: Configuración Java JDK

        usos: acciones/setup-java@v2.3.1

        con:

          distribución: 'zulú'

          versión java: '11'

        

      - usos: nttld/setup-ndk@v1

        con:

          Versión ndk: r15c

      # Ejecuta un conjunto de comandos usando el intérprete de comandos

      - nombre: línea de ejecución del script jaja

        ejecutar: |

          mkdir -p "%HAXELIB_ROOT%"

          configuración de haxelib "%HAXELIB_ROOT%"

          haxelib install lime 7.9.0 --quiet

          haxelib instalar openfl --quiet

          haxelib instalar flixel 4.9.0 --quiet

          haxelib instalar hxcpp --quiet

          haxelib ejecuta la configuración de cal

          haxelib ejecuta la configuración de lime ANDROID_SDK $ANDROID_SDK_ROOT

          haxelib ejecuta la configuración de lime ANDROID_NDK_ROOT $ANDROID_NDK_ROOT

          haxelib ejecutar configuración de cal JAVA_HOME $ JAVA_HOME

          haxelib ejecutar lime config ANDROID_SETUP verdadero

          haxelib instalar flixel-tools --quiet

          haxelib instalar flixel-ui --quiet

          haxelib instalar flixel-addons 2.10.0 --quiet

          haxelib instalar hscript --quiet

          haxelib git faxe https://github.com/uhrobots/faxe --quiet

          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet

          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet

          haxelib git extension-webview https://github.com/jigsaw-4277821/extension-webview --quiet

          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet

          haxelib instalar actuar

          lista haxelib

          

      - nombre: Registro de compilación

        ejecutar: |

          haxelib ejecuta la instalación de cal android

          haxelib ejecuta lime build android -final

          

      - usos: acciones/subir-artefacto@v2

        con:

          nombre: compilación de Android

          path: export/release/android/bin/app/build/outputs/apk/debug







